title: Inside My Bubble
author: TrinhBTo
email: totrinhbao@gmail.com

description: > # this means to ignore newlines until "baseurl:"

  
# social links
instagram_username: btrxnh # DO NOT include the @ character, or else the build will fail!
github_username:  TrinhBTo # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
